# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('staff', models.CharField(max_length=30, verbose_name='员工')),
                ('service', models.IntegerField(verbose_name='服务水平')),
                ('efficiency', models.IntegerField(verbose_name='办理效率')),
                ('message', models.TextField(blank=True, max_length=300, null=True, verbose_name='留言')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '值机科服务评价',
                'verbose_name_plural': '值机科服务评价',
            },
        ),
    ]
