# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='序号')),
                ('staff', models.CharField(max_length=30, verbose_name='员工')),
                ('star', models.IntegerField(verbose_name='评分')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='提交/修改时间')),
                ('ip_address', models.CharField(max_length=15, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '值机科服务评价',
                'verbose_name_plural': '值机科服务评价',
            },
        ),
    ]
