# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='ip_address',
            field=models.CharField(max_length=15, null=True, verbose_name='IP地址'),
        ),
    ]
