# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='details',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='座位号'),
        ),
        migrations.AddField(
            model_name='rate',
            name='flight',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='航班号'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='意见'),
        ),
    ]
