# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20180216_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='star',
        ),
        migrations.AddField(
            model_name='rate',
            name='eye_contact',
            field=models.IntegerField(default=0, verbose_name='目光交流'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='greeting',
            field=models.IntegerField(default=0, verbose_name='问候'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='smile',
            field=models.IntegerField(default=0, verbose_name='微笑'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
    ]
